import { useState } from "react";

type Urgency = "Low" | "Medium" | "High" | "Urgent / Critical";

const URGENCY_STYLES: Record<Urgency, string> = {
  "Low": "bg-[#ECFDF3] text-[#027A48]",
  "Medium": "bg-[#FFF9E6] text-[#B54708]",
  "High": "bg-[#FFF4ED] text-[#C4320A]",
  "Urgent / Critical": "bg-[#DC143C] text-white",
};

type CardField = {
  key: string;
  label: string;
  value: string;
  multiline?: boolean;
};

const INITIAL_FIELDS: CardField[] = [
  { key: "title", label: "Title", value: "Wrongful termination — Ramesh Sharma vs. Everest Trading Pvt. Ltd." },
  { key: "summary", label: "Summary of facts", value: "Client was employed as a senior accountant at Everest Trading Pvt. Ltd. for 4 years. On 14 July 2026, employment was terminated verbally with no written notice, no stated reason, and no severance offered. Client received no termination letter.", multiline: true },
  { key: "category", label: "Legal category", value: "Labour Law — Wrongful Termination" },
  { key: "dates", label: "Important dates", value: "Date of hire: July 2022\nDate of termination: 14 July 2026\nLast day worked: 14 July 2026", multiline: true },
  { key: "parties", label: "Parties involved", value: "Claimant: Ramesh Kumar Sharma\nRespondent: Everest Trading Pvt. Ltd., Kathmandu\nContact person: HR Manager (name unknown)", multiline: true },
  { key: "evidence", label: "Evidence available", value: "Employment contract (signed 2022)\nSalary slips for last 6 months\nNo termination letter received", multiline: true },
  { key: "missing", label: "Missing information", value: "Written reason for termination\nEmployer's HR policy documents\nInternal communication records", multiline: true },
  { key: "outcome", label: "Desired outcome", value: "Reinstatement to position, or full severance compensation as per Labour Act 2074.", multiline: true },
];

function EditIcon() {
  return (
    <svg width="14" height="14" fill="none" viewBox="0 0 24 24">
      <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
      <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

export default function CaseBriefScreen({ onBack, onFindLawyers }: { onBack: () => void; onFindLawyers: () => void }) {
  const [fields, setFields] = useState<CardField[]>(INITIAL_FIELDS);
  const [urgency, setUrgency] = useState<Urgency>("High");
  const [editingKey, setEditingKey] = useState<string | null>(null);
  const [editingUrgency, setEditingUrgency] = useState(false);
  const [globalEdit, setGlobalEdit] = useState(false);

  const updateField = (key: string, value: string) => {
    setFields((prev) => prev.map((f) => f.key === key ? { ...f, value } : f));
  };

  return (
    <div className="flex flex-col h-full bg-[#F2F4F7]">
      {/* Header */}
      <div className="bg-[#003893] px-5 pt-14 pb-5 flex-shrink-0">
        <div className="flex items-center gap-3 mb-1">
          <button onClick={onBack} className="text-white/80">
            <svg width="22" height="22" fill="none" viewBox="0 0 24 24">
              <path d="M19 12H5M12 5l-7 7 7 7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </button>
          <div className="flex-1">
            <h1 className="text-white text-lg font-semibold">Case Brief</h1>
            <p className="text-white/55 text-xs mt-0.5">AI-generated · Review carefully</p>
          </div>
          <button onClick={() => setGlobalEdit(!globalEdit)}
            className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition ${globalEdit ? "bg-white text-[#003893]" : "bg-white/15 text-white"}`}>
            <EditIcon />
            {globalEdit ? "Done" : "Edit"}
          </button>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mx-4 mt-3 flex-shrink-0 rounded-xl border border-[#C4320A]/25 bg-[#FFF4ED] px-4 py-3 flex items-start gap-2.5">
        <svg width="15" height="15" fill="none" viewBox="0 0 24 24" className="flex-shrink-0 text-[#C4320A] mt-0.5">
          <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" stroke="currentColor" strokeWidth="2" /><path d="M12 9v4M12 17h.01" stroke="currentColor" strokeWidth="2" strokeLinecap="round" />
        </svg>
        <p className="text-xs text-[#C4320A] font-medium leading-snug">
          Not final legal advice. This brief was generated by AI and should be reviewed by a qualified lawyer before taking any action.
        </p>
      </div>

      {/* Scrollable content */}
      <div className="flex-1 overflow-y-auto px-4 py-3 flex flex-col gap-3 pb-4">
        {/* Urgency card */}
        <div className="bg-white rounded-2xl p-4" style={{ boxShadow: "0 1px 4px rgba(0,0,0,0.07)" }}>
          <div className="flex items-center justify-between mb-2">
            <p className="text-xs font-semibold text-[#667085] uppercase tracking-wide">Urgency</p>
            {(globalEdit || editingUrgency) && (
              <button onClick={() => setEditingUrgency(!editingUrgency)} className="text-[#003893] text-xs font-medium">
                {editingUrgency ? "Done" : "Change"}
              </button>
            )}
          </div>
          <span className={`inline-flex px-3 py-1.5 rounded-full text-xs font-bold ${URGENCY_STYLES[urgency]}`}>
            {urgency}
          </span>
          {editingUrgency && (
            <div className="flex flex-wrap gap-2 mt-3 pt-3 border-t border-[#F2F4F7]">
              {(Object.keys(URGENCY_STYLES) as Urgency[]).map((u) => (
                <button key={u} onClick={() => { setUrgency(u); setEditingUrgency(false); }}
                  className={`px-3 py-1.5 rounded-full text-xs font-bold transition ${URGENCY_STYLES[u]} ${urgency === u ? "ring-2 ring-offset-1 ring-[#003893]" : "opacity-70"}`}>
                  {u}
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Field cards */}
        {fields.map((field) => {
          const isEditing = editingKey === field.key || globalEdit;
          return (
            <div key={field.key} className="bg-white rounded-2xl p-4" style={{ boxShadow: "0 1px 4px rgba(0,0,0,0.07)" }}>
              <div className="flex items-center justify-between mb-2">
                <p className="text-xs font-semibold text-[#667085] uppercase tracking-wide">{field.label}</p>
                {!globalEdit && (
                  <button onClick={() => setEditingKey(editingKey === field.key ? null : field.key)}
                    className="text-[#003893]">
                    <EditIcon />
                  </button>
                )}
              </div>
              {isEditing ? (
                <textarea
                  value={field.value}
                  onChange={(e) => updateField(field.key, e.target.value)}
                  className="w-full rounded-xl border border-[#003893]/30 bg-[#F9FAFB] px-3 py-2.5 text-sm text-[#1A1A1A] leading-relaxed resize-none focus:outline-none focus:ring-2 focus:ring-[#003893]/25 transition"
                  rows={field.multiline ? 4 : 2}
                />
              ) : (
                <p className="text-sm text-[#1A1A1A] leading-relaxed whitespace-pre-line">{field.value}</p>
              )}
            </div>
          );
        })}
      </div>

      {/* Bottom actions */}
      <div className="flex-shrink-0 px-4 py-4 bg-white border-t border-[#F2F4F7]" style={{ boxShadow: "0 -4px 16px rgba(0,0,0,0.06)" }}>
        <button onClick={onFindLawyers}
          className="w-full rounded-xl bg-[#003893] py-3.5 text-sm font-semibold text-white active:opacity-90 transition"
          style={{ boxShadow: "0 4px 16px rgba(0,56,147,0.28)" }}>
          Approve & find lawyers →
        </button>
        <p className="text-center text-[11px] text-[#98A2B3] mt-2.5">
          Your brief will be shared with matched lawyers only
        </p>
      </div>
    </div>
  );
}
